a = int(input("введите сторону а >>>"))
b = int(input("введите сторону b >>>"))
c = int(input("введите сторону с >>>"))
an = (input ("введите угол А >>>"))
p = int((a+b+c)/2)
print ("полупериметр = ", p)
print ('nadeyus rabotae')